services:
  mariadb:
    image: mariadb:10.9.2
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: food-reservation
    ports:
      - "3306:3306"
  app:
    # https://docs.docker.com/compose/compose-file/#interpolation
    # ${IMAGE_NAME}, ${JEP} 는 docker compose 를 실행시키는 서버의 환경변수로부터 받아옵니다.
    image: ${IMAGE_NAME}
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080"
    deploy:
      replicas: 2
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JEP: ${JEP}
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/food-reservation
  nginx:
    image: nginx:1.23.1
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
